Loan word classification experiments

In [1]:
import sklearn as sk
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier
import pandas as pd 
import numpy as np 
import io
import requests
import csv
import json
from sklearn.model_selection import StratifiedShuffleSplit
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import precision_recall_fscore_support as score
from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, classification_report, confusion_matrix
import pprint
import matplotlib.pyplot as plt
import random

In [2]:
import torch
from torch import nn
from torch import optim
from sklearn.model_selection import train_test_split

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")
# device = 'cpu'
# print(device)

Using cuda device


In [4]:
pairs = None

with open('../language-pairs.json', 'r') as f:
    pairs = json.loads(f.read())
    print(pairs)
    
train_alldata = {}
test_alldata = {}

train_realdist = {}
test_realdist = {}

train_balanced = {}
test_balanced = {}

for pair in pairs:
    print(pair)
    L1 = pairs[pair]['target']['name']
    L2 = pairs[pair]['source']['name']

    # load datasets
    prefix = f'../Datasets/production_train_test/{L1}-{L2}'

    train_alldata[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/alldata/{L1}-{L2}-train_production_alldata.csv')
    test_alldata[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/alldata/{L1}-{L2}-test_production_alldata.csv')

    train_realdist[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/realdist/{L1}-{L2}-train_production_realdist.csv')
    test_realdist[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/realdist/{L1}-{L2}-test_production_realdist.csv')

    train_balanced[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/balanced/{L1}-{L2}-train_production_balanced.csv')
    test_balanced[f'{L1}-{L2}'] = pd.read_csv(f'{prefix}/balanced/{L1}-{L2}-test_production_balanced.csv')
    
    
features = ['Fast Levenshtein Distance Div Maxlen',
            'Dolgo Prime Distance Div Maxlen',
            'Feature Edit Distance Div Maxlen',
            'Hamming Feature Distance Div Maxlen',
            'Weighted Feature Distance Div Maxlen',
            'Partial Hamming Feature Distance Div Maxlen',
            'plain Levenshtein',
            'DNN_logits',
            'MBERT_cos_sim',
            'XLM_cos_sim'
           ]


# features = ['Fast Levenshtein Distance Div Maxlen',
#             'Dolgo Prime Distance Div Maxlen',
#             'Feature Edit Distance Div Maxlen',
#             'Hamming Feature Distance Div Maxlen',
#             'Weighted Feature Distance Div Maxlen',
#             'Partial Hamming Feature Distance Div Maxlen',
#             'plain Levenshtein',
             
#            ]




# features = [ 
#             'plain Levenshtein',
#             'DNN_logits',
#             'MBERT_cos_sim',
#             'XLM_cos_sim'
#            ]


# features = [ 
#             'plain Levenshtein',
             
#             'MBERT_cos_sim',
#             'XLM_cos_sim'
#            ]

# features = [ 
            
#                 'DNN_logits',
             
#             'MBERT_cos_sim',
#             'XLM_cos_sim'
#            ]
# features = [ 
#             'Partial Hamming Feature Distance Div Maxlen',
#             'plain Levenshtein',
#                 'DNN_logits',
             
#             'MBERT_cos_sim',
#             'XLM_cos_sim'
#            ]


labels = ['label_bin']

train_allpairs_alldata = pd.concat([train_alldata[pair] for pair in pairs])
x_train_allpairs_alldata = np.hstack([train_allpairs_alldata[features].values])
y_train_allpairs_alldata = train_allpairs_alldata[labels].values.ravel()
x_train_allpairs_alldata_means = np.mean(x_train_allpairs_alldata, axis=1).reshape(-1,1)
x_train_allpairs_alldata_stds = np.std(x_train_allpairs_alldata, axis=1).reshape(-1,1)

test_allpairs_alldata = pd.concat([test_alldata[pair] for pair in pairs])
x_test_allpairs_alldata = np.hstack([test_allpairs_alldata[features].values])
y_test_allpairs_alldata = test_allpairs_alldata[labels].values.ravel()

train_allpairs_realdist = pd.concat([train_realdist[pair] for pair in pairs])
x_train_allpairs_realdist = np.hstack([train_allpairs_realdist[features].values])
y_train_allpairs_realdist = train_allpairs_realdist[labels].values.ravel()
x_train_allpairs_realdist_means = np.mean(x_train_allpairs_realdist, axis=1).reshape(-1,1)
x_train_allpairs_realdist_stds = np.std(x_train_allpairs_realdist, axis=1).reshape(-1,1)

test_allpairs_realdist = pd.concat([test_realdist[pair] for pair in pairs])
x_test_allpairs_realdist = np.hstack([test_allpairs_realdist[features].values])
y_test_allpairs_realdist = test_allpairs_realdist[labels].values.ravel()

train_allpairs_balanced = pd.concat([train_balanced[pair] for pair in pairs])
x_train_allpairs_balanced = np.hstack([train_allpairs_balanced[features].values])
y_train_allpairs_balanced = train_allpairs_balanced[labels].values.ravel()
x_train_allpairs_balanced_means = np.mean(x_train_allpairs_balanced, axis=1).reshape(-1,1)
x_train_allpairs_balanced_stds = np.std(x_train_allpairs_balanced, axis=1).reshape(-1,1)

test_allpairs_balanced = pd.concat([test_balanced[pair] for pair in pairs])
x_test_allpairs_balanced = np.hstack([test_allpairs_balanced[features].values])
y_test_allpairs_balanced = test_allpairs_balanced[labels].values.ravel()

{'Hindi-Persian': {'target': {'name': 'Hindi', 'epi': 'hin-Deva', 'gtrans': 'hi', 'unicode': 'Devanagari'}, 'source': {'name': 'Persian', 'epi': 'fas-Arab', 'gtrans': 'fa', 'unicode': 'Arabic'}, 'wiki': 'https://en.m.wiktionary.org/wiki/Category:Hindi_terms_borrowed_from_Persian'}, 'English-French': {'target': {'name': 'English', 'epi': 'eng-Latn', 'gtrans': 'en', 'unicode': 'Latin'}, 'source': {'name': 'French', 'epi': 'fra-Latn', 'gtrans': 'fr', 'unicode': 'Latin'}, 'wiki': 'https://en.m.wiktionary.org/wiki/Category:English_terms_borrowed_from_French'}}
Hindi-Persian
English-French


# Logistic Regression classifier

In [5]:
def lr_evaluate(full_train_set, full_test_set, pairs_list):    
    train_set = pd.concat([full_train_set[pair] for pair in pairs])
    x_train = train_set[features].values
    x_means = np.mean(x_train, axis=0)
    x_stds = np.std(x_train, axis=0)
    y_train = train_set[labels].values.ravel()
    
    test_set = pd.concat([full_test_set[pair] for pair in pairs])
    x_test = test_set[features].values
    y_test = test_set[labels].values.ravel()
    
    # standardize input features
    x_train = (x_train - x_means)/x_stds

    print("Training on all langs\n")
    LR = LogisticRegression(random_state=1, solver='lbfgs', multi_class='ovr', max_iter=500).fit(x_train, y_train)

    # display regressor weights
    df = pd.DataFrame(LR.coef_, columns=features).style.set_caption('Weights')
    display(df)
    print()
    
    print("Evaluating on all langs")
    x_test = (x_test - x_means)/x_stds
    y_pred = LR.predict(x_test)

    print("f1-score : ", f1_score(y_test, y_pred ))
    print("precision : ",precision_score(y_test, y_pred))
    print("recall : ",recall_score(y_test, y_pred )) 
    print("accuracy : ",accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print()
    
    # display false positives and false negatives
    unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
    tp = np.array(np.where(unq == 3)).tolist()[0]
    fp = np.array(np.where(unq == 1)).tolist()[0]
    tn = np.array(np.where(unq == 0)).tolist()[0]
    fn = np.array(np.where(unq == 2)).tolist()[0]

    display(test_set.reset_index(drop=True).iloc[fp,:].style.set_caption('False positives'))
    display(test_set.reset_index(drop=True).iloc[fn,:].style.set_caption('False negatives'))
    
    for pair in pairs_list:
        print(f'Evaluating on {pair}')
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_test = (x_test - x_means)/x_stds
        y_pred = LR.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))
        
    for pair in pairs_list:
        print(f'Training and evaluating on {pair}')
        
        train_set = full_train_set[pair]
        x_train = train_set[features].values
        x_means = np.mean(x_train, axis=0)
        x_stds = np.std(x_train, axis=0)
        y_train = train_set[labels].values.ravel()
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_train = (x_train - x_means)/x_stds
        
        LR = LogisticRegression(random_state=1, solver='lbfgs', multi_class='ovr', max_iter=500).fit(x_train, y_train)
        
        # display regressor weights
        df = pd.DataFrame(LR.coef_, columns=features).style.set_caption('Weights')
        display(df)

        x_test = (x_test - x_means)/x_stds
        y_pred = LR.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))

In [6]:
print("Evaluating on alldata splits\n")
lr_evaluate(train_alldata, test_alldata, pairs)

print("Evaluating on realdist splits\n")
lr_evaluate(train_realdist, test_realdist, pairs)

print("Evaluating on balanced splits\n")
lr_evaluate(train_balanced, test_balanced, pairs)

Evaluating on alldata splits

Training on all langs




Evaluating on all langs
f1-score :  0.7360970677451971
precision :  0.7711864406779662
recall :  0.7040618955512572
accuracy :  0.9122689075630253
              precision    recall  f1-score   support

           0       0.94      0.96      0.95      2458
           1       0.77      0.70      0.74       517

    accuracy                           0.91      2975
   macro avg       0.86      0.83      0.84      2975
weighted avg       0.91      0.91      0.91      2975

[[2350  108]
 [ 153  364]]



Evaluating on Hindi-Persian
f1-score :  0.7520661157024793
precision :  0.8504672897196262
recall :  0.674074074074074
accuracy :  0.9545454545454546
              precision    recall  f1-score   support

           0       0.96      0.99      0.97      1185
           1       0.85      0.67      0.75       135

    accuracy                           0.95      1320
   macro avg       0.91      0.83      0.86      1320
weighted avg       0.95      0.95      0.95      1320

[[1169   16]
 [  44   91]]



Evaluating on English-French
f1-score :  0.7309236947791165
precision :  0.7479452054794521
recall :  0.7146596858638743
accuracy :  0.8785498489425981
              precision    recall  f1-score   support

           0       0.92      0.93      0.92      1273
           1       0.75      0.71      0.73       382

    accuracy                           0.88      1655
   macro avg       0.83      0.82      0.83      1655
weighted avg       0.88      0.88      0.88      1655

[[1181   92]
 [ 109  273]]



Training and evaluating on Hindi-Persian


f1-score :  0.7407407407407407
precision :  0.7407407407407407
recall :  0.7407407407407407
accuracy :  0.946969696969697
              precision    recall  f1-score   support

           0       0.97      0.97      0.97      1185
           1       0.74      0.74      0.74       135

    accuracy                           0.95      1320
   macro avg       0.86      0.86      0.86      1320
weighted avg       0.95      0.95      0.95      1320

[[1150   35]
 [  35  100]]



Training and evaluating on English-French


f1-score :  0.7721691678035472
precision :  0.8062678062678063
recall :  0.7408376963350786
accuracy :  0.8990936555891239
              precision    recall  f1-score   support

           0       0.92      0.95      0.94      1273
           1       0.81      0.74      0.77       382

    accuracy                           0.90      1655
   macro avg       0.87      0.84      0.85      1655
weighted avg       0.90      0.90      0.90      1655

[[1205   68]
 [  99  283]]



Evaluating on realdist splits

Training on all langs




Evaluating on all langs
f1-score :  0.8891235480464624
precision :  0.9790697674418605
recall :  0.8143133462282398
accuracy :  0.8905109489051095
              precision    recall  f1-score   support

           0       0.82      0.98      0.89       442
           1       0.98      0.81      0.89       517

    accuracy                           0.89       959
   macro avg       0.90      0.90      0.89       959
weighted avg       0.91      0.89      0.89       959

[[433   9]
 [ 96 421]]



Evaluating on Hindi-Persian
f1-score :  0.9047619047619048
precision :  0.9743589743589743
recall :  0.8444444444444444
accuracy :  0.9466666666666667
              precision    recall  f1-score   support

           0       0.94      0.99      0.96       315
           1       0.97      0.84      0.90       135

    accuracy                           0.95       450
   macro avg       0.96      0.92      0.93       450
weighted avg       0.95      0.95      0.95       450

[[312   3]
 [ 21 114]]



Evaluating on English-French
f1-score :  0.883453237410072
precision :  0.9808306709265175
recall :  0.8036649214659686
accuracy :  0.8408644400785854
              precision    recall  f1-score   support

           0       0.62      0.95      0.75       127
           1       0.98      0.80      0.88       382

    accuracy                           0.84       509
   macro avg       0.80      0.88      0.82       509
weighted avg       0.89      0.84      0.85       509

[[121   6]
 [ 75 307]]



Training and evaluating on Hindi-Persian


f1-score :  0.9266409266409267
precision :  0.967741935483871
recall :  0.8888888888888888
accuracy :  0.9577777777777777
              precision    recall  f1-score   support

           0       0.95      0.99      0.97       315
           1       0.97      0.89      0.93       135

    accuracy                           0.96       450
   macro avg       0.96      0.94      0.95       450
weighted avg       0.96      0.96      0.96       450

[[311   4]
 [ 15 120]]



Training and evaluating on English-French


f1-score :  0.8939828080229226
precision :  0.9873417721518988
recall :  0.8167539267015707
accuracy :  0.8546168958742633
              precision    recall  f1-score   support

           0       0.64      0.97      0.77       127
           1       0.99      0.82      0.89       382

    accuracy                           0.85       509
   macro avg       0.81      0.89      0.83       509
weighted avg       0.90      0.85      0.86       509

[[123   4]
 [ 70 312]]



Evaluating on balanced splits

Training on all langs




Evaluating on all langs
f1-score :  0.911550468262227
precision :  0.9864864864864865
recall :  0.8471953578336557
accuracy :  0.8797736916548797
              precision    recall  f1-score   support

           0       0.70      0.97      0.81       190
           1       0.99      0.85      0.91       517

    accuracy                           0.88       707
   macro avg       0.84      0.91      0.86       707
weighted avg       0.91      0.88      0.88       707

[[184   6]
 [ 79 438]]



Evaluating on Hindi-Persian
f1-score :  0.9254901960784313
precision :  0.9833333333333333
recall :  0.8740740740740741
accuracy :  0.9298892988929889
              precision    recall  f1-score   support

           0       0.89      0.99      0.93       136
           1       0.98      0.87      0.93       135

    accuracy                           0.93       271
   macro avg       0.94      0.93      0.93       271
weighted avg       0.94      0.93      0.93       271

[[134   2]
 [ 17 118]]



Evaluating on English-French
f1-score :  0.9065155807365438
precision :  0.9876543209876543
recall :  0.837696335078534
accuracy :  0.8486238532110092
              precision    recall  f1-score   support

           0       0.45      0.93      0.60        54
           1       0.99      0.84      0.91       382

    accuracy                           0.85       436
   macro avg       0.72      0.88      0.75       436
weighted avg       0.92      0.85      0.87       436

[[ 50   4]
 [ 62 320]]



Training and evaluating on Hindi-Persian


f1-score :  0.9425287356321839
precision :  0.9761904761904762
recall :  0.9111111111111111
accuracy :  0.9446494464944649
              precision    recall  f1-score   support

           0       0.92      0.98      0.95       136
           1       0.98      0.91      0.94       135

    accuracy                           0.94       271
   macro avg       0.95      0.94      0.94       271
weighted avg       0.95      0.94      0.94       271

[[133   3]
 [ 12 123]]



Training and evaluating on English-French


f1-score :  0.9119318181818181
precision :  0.9968944099378882
recall :  0.8403141361256544
accuracy :  0.8577981651376146
              precision    recall  f1-score   support

           0       0.46      0.98      0.63        54
           1       1.00      0.84      0.91       382

    accuracy                           0.86       436
   macro avg       0.73      0.91      0.77       436
weighted avg       0.93      0.86      0.88       436

[[ 53   1]
 [ 61 321]]



# Neural Network classifier

## Definition

In [ ]:
class NeuralNetwork(nn.Module):
    def __init__(self, n_features):
        super(NeuralNetwork, self).__init__()
        self.linear_relu_stack = nn.Sequential(
            nn.Linear(n_features, 256),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(256, 128),
            nn.ReLU(),
            nn.Dropout(0.1),
            nn.Linear(128, 1),
            
        )

    def forward(self, x):
        logits_new = self.linear_relu_stack(x)
        logits  = logits_new
        
        return torch.sigmoid(logits), logits_new
    
    def fit(self, X_train, Y_train, X_val, Y_val, criterion, optimizer, n_epochs=5000):
        train_losses = []
        val_losses = []
        train_accur = []
        val_accur = []

        for epoch in range(n_epochs):
            y_pred, logits = self(X_train.float())

            train_loss = criterion(y_pred, Y_train.float())

            if epoch % (n_epochs // 50) == 0:
                train_acc,_ = self.calculate_accuracy(Y_train, y_pred)

                y_val_pred = self(X_val.float())[0]

                val_loss = criterion(y_val_pred, Y_val.float())

                val_acc, total_corr = self.calculate_accuracy(Y_val, y_val_pred)

                print(f'''epoch {epoch}
                    Train set - loss: {self.round_tensor(train_loss)}, accuracy: {self.round_tensor(train_acc)} 
                    Val set - loss: {self.round_tensor(val_loss)}, accuracy: {self.round_tensor(val_acc)}''')
                
                train_losses.append(train_loss.detach().cpu().numpy())
                val_losses.append(val_loss.detach().cpu().numpy())

                val_accur.append(val_acc.detach().cpu().numpy())
                train_accur.append(train_acc.detach().cpu().numpy())

            optimizer.zero_grad()

            train_loss.backward()

            optimizer.step()
            
        return train_losses,val_losses,train_accur,val_accur
    
    def calculate_accuracy(self, y_true, y_pred):
        predicted = y_pred.ge(.5) 
        return ((y_true == predicted).sum().float() / len(y_true), (y_true == predicted).sum())
    
    def round_tensor(self, t, decimal_places=3):
        return round(t.item(), decimal_places)
    
    def plot_losses(self, train_losses, val_losses, train_accur, val_accur):
        epochs = range(1, len(train_accur) + 1)

        plt.plot(epochs, train_accur, 'bo', label='Training acc')
        plt.plot(epochs, val_accur, 'b', label='Vaidation acc')
        plt.title('Training and validation accuracy')
        plt.legend()

        plt.figure()

        plt.plot(epochs, train_losses, 'bo', label='Training loss')
        plt.plot(epochs, val_losses, 'b', label='Validation loss')
        plt.title('Training and validation loss')
        plt.legend()

        plt.show()

In [ ]:
def nn_evaluate(full_train_set, full_test_set, pairs_list):    
    train_set = pd.concat([full_train_set[pair] for pair in pairs])
    x_train = train_set[features].values
    x_means = np.mean(x_train, axis=0)
    x_stds = np.std(x_train, axis=0)
    y_train = train_set[labels].values.ravel()
    
    test_set = pd.concat([full_test_set[pair] for pair in pairs])
    x_test = test_set[features].values
    y_test = test_set[labels].values.ravel()
    
    # standardize input features
    x_train = (x_train - x_means)/x_stds
    
    torch.manual_seed(7)
    random.seed(7)
    np.random.seed(7)
    
    model = NeuralNetwork(x_train.shape[1]).to(device)
    print(model)
    
    criterion = nn.BCELoss().to(device)
    optimizer = optim.Adam(model.parameters(), lr=0.00001)
    #optimizer = optim.SGD(model.parameters(),lr=0.00001, momentum=0.0,  weight_decay=0.0, nesterov=False)
    
    x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=1, stratify=y_train)

    x_train = torch.tensor(x_train).to(device)
    x_val = torch.tensor(x_val).to(device)
    y_train = torch.tensor(y_train).reshape(-1,1).to(device)
    y_val = torch.tensor(y_val).reshape(-1,1).to(device)
        
    print("Training on all langs\n")
    train_losses, val_losses, train_accur, val_accur = \
        model.fit(x_train, y_train, x_val, y_val, criterion, optimizer, n_epochs=5000)
    model.plot_losses(train_losses,val_losses,train_accur,val_accur)
    
    model.eval()
    
    x_test = (x_test - x_means)/x_stds
    x_test = torch.tensor(x_test).to(device)

    with torch.no_grad():
        y_pred = model(torch.tensor(x_test).float())[0] > .5
        y_pred = y_pred.detach().cpu().numpy()

        print("f1-score : ", f1_score(y_test, y_pred))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred)) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        #display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.reset_index(drop=True).iloc[fp,:].style.set_caption('False positives'))
        display(test_set.reset_index(drop=True).iloc[fn,:].style.set_caption('False negatives'))
        #display(test_set.iloc[fn,:].style.set_caption('False negatives'))
        
        for pair in pairs_list:
            print(f'Evaluating on {pair}')

            test_set = full_test_set[pair]
            x_test = test_set[features].values
            y_test = test_set[labels].values.ravel()

            x_test = (x_test - x_means)/x_stds
            x_test = torch.tensor(x_test).to(device)
            y_pred = model(torch.tensor(x_test).float())[0] > .5
            y_pred = y_pred.detach().cpu().numpy()
            
 
            print("f1-score : ", f1_score(y_test, y_pred ))
            print("precision : ",precision_score(y_test, y_pred))
            print("recall : ",recall_score(y_test, y_pred )) 
            print("accuracy : ",accuracy_score(y_test, y_pred))
            print(classification_report(y_test, y_pred))
            print(confusion_matrix(y_test, y_pred))
            print()
            
            # display false positives and false negatives
            unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
            tp = np.array(np.where(unq == 3)).tolist()[0]
            fp = np.array(np.where(unq == 1)).tolist()[0]
            tn = np.array(np.where(unq == 0)).tolist()[0]
            fn = np.array(np.where(unq == 2)).tolist()[0]

            display(test_set.iloc[fp,:].style.set_caption('False positives'))
            display(test_set.iloc[fn,:].style.set_caption('False negatives'))
            
    for pair in pairs_list:
        print(f'Training and evaluating on {pair}')
        
        train_set = full_train_set[pair]
        x_train = train_set[features].values
        x_means = np.mean(x_train, axis=0)
        x_stds = np.std(x_train, axis=0)
        y_train = train_set[labels].values.ravel()
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_train = (x_train - x_means)/x_stds
        
        model = NeuralNetwork(x_train.shape[1]).to(device)
    
        criterion = nn.BCELoss().to(device)
        optimizer = optim.Adam(model.parameters(), lr=0.00001)

        x_train, x_val, y_train, y_val = train_test_split(x_train, y_train, test_size=0.2, random_state=1, stratify=y_train)

        x_train = torch.tensor(x_train).to(device)
        x_val = torch.tensor(x_val).to(device)
        y_train = torch.tensor(y_train).reshape(-1,1).to(device)
        y_val = torch.tensor(y_val).reshape(-1,1).to(device)

        train_losses, val_losses, train_accur, val_accur = \
            model.fit(x_train, y_train, x_val, y_val, criterion, optimizer, n_epochs=5000)
        model.plot_losses(train_losses,val_losses,train_accur,val_accur)

        model.eval()

        x_test = (x_test - x_means)/x_stds
        x_test = torch.tensor(x_test).to(device)
        
        with torch.no_grad():
            y_pred = model(torch.tensor(x_test).float())[0] > .5
            y_pred = y_pred.detach().cpu().numpy()

            print("f1-score : ", f1_score(y_test, y_pred ))
            print("precision : ",precision_score(y_test, y_pred))
            print("recall : ",recall_score(y_test, y_pred )) 
            print("accuracy : ",accuracy_score(y_test, y_pred))
            print(classification_report(y_test, y_pred))
            print(confusion_matrix(y_test, y_pred))
            print()
            
            # display false positives and false negatives
            unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
            tp = np.array(np.where(unq == 3)).tolist()[0]
            fp = np.array(np.where(unq == 1)).tolist()[0]
            tn = np.array(np.where(unq == 0)).tolist()[0]
            fn = np.array(np.where(unq == 2)).tolist()[0]

            display(test_set.iloc[fp,:].style.set_caption('False positives'))
            display(test_set.iloc[fn,:].style.set_caption('False negatives'))

In [ ]:
print("Evaluating on alldata splits\n")
nn_evaluate(train_alldata, test_alldata, pairs)

print("Evaluating on realdist splits\n")
nn_evaluate(train_realdist, test_realdist, pairs)

print("Evaluating on balanced splits\n")
nn_evaluate(train_balanced, test_balanced, pairs)

# SVM Classifier

In [ ]:
def svm_evaluate(full_train_set, full_test_set, pairs_list):    
    train_set = pd.concat([full_train_set[pair] for pair in pairs])
    x_train = train_set[features].values
    x_means = np.mean(x_train, axis=0)
    x_stds = np.std(x_train, axis=0)
    y_train = train_set[labels].values.ravel()
    
    test_set = pd.concat([full_test_set[pair] for pair in pairs])
    x_test = test_set[features].values
    y_test = test_set[labels].values.ravel()
    
    # standardize input features
    x_train = (x_train - x_means)/x_stds

    print("Training on all langs\n")
     
    SVM = SVC(kernel='linear')
    SVM.fit(x_train, y_train)

    # display regressor weights
    df = pd.DataFrame(SVM.coef_, columns=features).style.set_caption('Weights')
    display(df)
    print()
    
    print("Evaluating on all langs")
    x_test = (x_test - x_means)/x_stds
    y_pred = SVM.predict(x_test)

    print("f1-score : ", f1_score(y_test, y_pred ))
    print("precision : ",precision_score(y_test, y_pred))
    print("recall : ",recall_score(y_test, y_pred )) 
    print("accuracy : ",accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print()
    
    # display false positives and false negatives
    unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
    tp = np.array(np.where(unq == 3)).tolist()[0]
    fp = np.array(np.where(unq == 1)).tolist()[0]
    tn = np.array(np.where(unq == 0)).tolist()[0]
    fn = np.array(np.where(unq == 2)).tolist()[0]

    display(test_set.reset_index(drop=True).iloc[fp,:].style.set_caption('False positives'))
    display(test_set.reset_index(drop=True).iloc[fn,:].style.set_caption('False negatives'))
    
    for pair in pairs_list:
        print(f'Evaluating on {pair}')
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_test = (x_test - x_means)/x_stds
        y_pred = SVM.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))
        
    for pair in pairs_list:
        print(f'Training and evaluating on {pair}')
        
        train_set = full_train_set[pair]
        x_train = train_set[features].values
        x_means = np.mean(x_train, axis=0)
        x_stds = np.std(x_train, axis=0)
        y_train = train_set[labels].values.ravel()
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_train = (x_train - x_means)/x_stds
        
        SVM = SVC(kernel='linear')
        SVM.fit(x_train, y_train)
        
        # display regressor weights
        df = pd.DataFrame(SVM.coef_, columns=features).style.set_caption('Weights')
        display(df)

        x_test = (x_test - x_means)/x_stds
        y_pred = SVM.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))

In [ ]:
print("Evaluating on alldata splits\n")
svm_evaluate(train_alldata, test_alldata, pairs)

print("Evaluating on realdist splits\n")
svm_evaluate(train_realdist, test_realdist, pairs)

print("Evaluating on balanced splits\n")
svm_evaluate(train_balanced, test_balanced, pairs)

# Random Forest Classifier 

In [ ]:
def rf_evaluate(full_train_set, full_test_set, pairs_list):    
    train_set = pd.concat([full_train_set[pair] for pair in pairs])
    x_train = train_set[features].values
    x_means = np.mean(x_train, axis=0)
    x_stds = np.std(x_train, axis=0)
    y_train = train_set[labels].values.ravel()
    
    test_set = pd.concat([full_test_set[pair] for pair in pairs])
    x_test = test_set[features].values
    y_test = test_set[labels].values.ravel()
    
    # standardize input features
    x_train = (x_train - x_means)/x_stds

    print("Training on all langs\n")
     
    RF = RandomForestClassifier(n_estimators=1000, max_depth=5, random_state=0)
    RF.fit(x_train, y_train)
#     num_leafs = [1, 5, 10, 20, 50, 100]
#     parameters3 = [{'n_estimators' : range(100,800,20),
#              'max_depth': range(1,20,5),
#              'min_samples_leaf':num_leafs
#              }]
    
#     gs3 = GridSearchCV(estimator=RF,
#                   param_grid=parameters3,
#                   cv = 10,
#                   n_jobs = -1)

#     gs3.fit(x_train, y_train)
    
    # display regressor weights
    #df = pd.DataFrame(RF.best_params_, columns=features).style.set_caption('Weights')
    #display(df)
    print()
    
    print("Evaluating on all langs")
    x_test = (x_test - x_means)/x_stds
    y_pred = RF.predict(x_test)

    print("f1-score : ", f1_score(y_test, y_pred ))
    print("precision : ",precision_score(y_test, y_pred))
    print("recall : ",recall_score(y_test, y_pred )) 
    print("accuracy : ",accuracy_score(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))
    print()
    
    # display false positives and false negatives
    unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
    tp = np.array(np.where(unq == 3)).tolist()[0]
    fp = np.array(np.where(unq == 1)).tolist()[0]
    tn = np.array(np.where(unq == 0)).tolist()[0]
    fn = np.array(np.where(unq == 2)).tolist()[0]

    display(test_set.reset_index(drop=True).iloc[fp,:].style.set_caption('False positives'))
    display(test_set.reset_index(drop=True).iloc[fn,:].style.set_caption('False negatives'))
    
    for pair in pairs_list:
        print(f'Evaluating on {pair}')
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_test = (x_test - x_means)/x_stds
        y_pred = RF.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))
        
    for pair in pairs_list:
        print(f'Training and evaluating on {pair}')
        
        train_set = full_train_set[pair]
        x_train = train_set[features].values
        x_means = np.mean(x_train, axis=0)
        x_stds = np.std(x_train, axis=0)
        y_train = train_set[labels].values.ravel()
        
        test_set = full_test_set[pair]
        x_test = test_set[features].values
        y_test = test_set[labels].values.ravel()
        
        x_train = (x_train - x_means)/x_stds
        
        RF = RandomForestClassifier(n_estimators=1000, max_depth=5, random_state=0)
        RF.fit(x_train, y_train)
#         num_leafs = [1, 5, 10, 20, 50, 100]
#         parameters3 = [{'n_estimators' : range(100,800,20),
#              'max_depth': range(1,20,5),
#              'min_samples_leaf':num_leafs
#              }]
    
#         gs3 = GridSearchCV(estimator=RF,
#                   param_grid=parameters3,
#                   cv = 10,
#                   n_jobs = -1)

#         gs3.fit(x_train, y_train)
        
        # display regressor weights
        #df = pd.DataFrame(RF.best_params_, columns=features).style.set_caption('Weights')
        #display(df)

        x_test = (x_test - x_means)/x_stds
        y_pred = RF.predict(x_test)
        
        print("f1-score : ", f1_score(y_test, y_pred ))
        print("precision : ",precision_score(y_test, y_pred))
        print("recall : ",recall_score(y_test, y_pred )) 
        print("accuracy : ",accuracy_score(y_test, y_pred))
        print(classification_report(y_test, y_pred))
        print(confusion_matrix(y_test, y_pred))
        print()
        
        # display false positives and false negatives
        unq = np.array([x + 2*y for x, y in zip(y_pred, y_test)])
        tp = np.array(np.where(unq == 3)).tolist()[0]
        fp = np.array(np.where(unq == 1)).tolist()[0]
        tn = np.array(np.where(unq == 0)).tolist()[0]
        fn = np.array(np.where(unq == 2)).tolist()[0]

        display(test_set.iloc[fp,:].style.set_caption('False positives'))
        display(test_set.iloc[fn,:].style.set_caption('False negatives'))

In [ ]:
print("Evaluating on alldata splits\n")
rf_evaluate(train_alldata, test_alldata, pairs)

print("Evaluating on realdist splits\n")
rf_evaluate(train_realdist, test_realdist, pairs)

print("Evaluating on balanced splits\n")
rf_evaluate(train_balanced, test_balanced, pairs)